[package]
name = "sbyte"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "Console-based byte editor"
repository = "https://github.com/quintinfsmith/sbyte.git"
license = "GPL-3.0"

[dependencies]
wrecked = { git = "https://github.com/quintinfsmith/wrecked", version ="^0.1.10" }
ctrlc = "3.1.6"


