[package]
name = "sbyte"
version = "0.2.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wrecked = { path = "/home/pent/Projects/100" }
termios = "0.3"
